language: python
python:
  - "2.7"

dist: trusty
sudo: required
 
cache: pip
install:
 - pip install biopython
 - pip install mygene
 - pip install selenium
 
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 
before_install:  
 - export CHROME_BIN=/usr/bin/google-chrome 
 - sudo apt-get update 
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
 - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
 - sudo apt-get update
 - sudo apt-get install google-chrome-stable
 
env:
 global:
    - CHROME_REVISION=`curl -s http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/LAST_CHANGE`
    - CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
    - PATH=$PATH:$PWD/chrome-linux
 
script:
 - export CHROME_REVISION=`curl -s http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/LAST_CHANGE`
 - export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
 - curl -L -O "http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/${CHROME_REVISION}/chrome-linux.zip"
 - unzip chrome-linux.zip

 - curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
 - unzip -o chromedriver_linux64.zip

 - chmod +x chromedriver
 - mv chromedriver chrome-linux/chromedriver
 - export PATH=$PATH:$PWD/chrome-linux

 - export CHROME_BINARY=$PWD/chrome-linux/chrome
 - export CHROMEDRIVER=$PWD/chrome-linux/chromedriver
 - python Starter.py new_data_filtered2.csv
 - zip -r Output.zip $TRAVIS_BUILD_DIR/Output
  
deploy:
  provider: releases
  api_key:
    secure: "QTcJ4qzTL2hsfJ0l+nymC4FwmAJtxwuJWTITEZUmKE2UP9PhFoFWt1i14UD0LX6JukCnLzJSRNocbUULv3M6IhcoB+iDGTjLVAe48o3Hy8K09M3za5T+hIThB+Vh/F5HmQ9tguotKkjofrcKgtzuGWXhLY7r7EGEpFoj4N3TpnPxjtwB7MV1oCFD2cs7Zu9bqiUBnySHuUxZeyS1PApfU+wA9gKy3ryEaIw73GtnlazBgFl5+Phs2E5CdTJYD+B9fgbiXnXpBybnEwMpDq9/O67m5nUW0oKreu4LZUtubDQRRDePE8cwW/XXf0kRf9wGQgMDvB02NmAovK6l05TVnk47+3jpSm8k/lw5PjL4M36Fw8EGWehtqu1QbRKR+lIO9xr/mkbJSU97OmLU5FSQR56BE4iLf6FOuU/TfC+iJwEdcdV+rd40jh3Ut4yufdKqFj3DvGhxu4uhwARhT+Hs2bmF0M2L0oAw9yN+DOaImBx8voN6Opvl8RCIW8wULEjcwXqsY8bQJfaKXaxVWViUKyut29tp/3C04A7TBPGSIh/WnXogxQPZNbrd4TNPAjSYstkUb5znkIusuBfot8r3KBVwSnlLUFiVvnYsDZEAPkUTgdfNQQ2aBTA8ulnDS0/T+eImkzpF1f/G67G5aU4WHolO9BKm+Y1VJDe08i8vVm4=" 
  file: Output.zip
  skip_cleanup: true
  on:
    repo: dcolam/rna_binding_proteins_batchanalyzer
    tags: true
    
notifications:
 on success: never

