language: python
python:
  - "2.7"
  
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
  
cache: pip
install:
  - pip install biopython
  - pip install mygene
  - pip install selenium
  
script:
  - python rna_binding_proteins_batchanalyzer/Starter.py rna_binding_proteins_batchanalyzer/Gene_acd_ensemble_ID.csv
