language: python
python:
  - "2.7"
  
dist: trusty
sudo: required

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "6"
cache:
  directories: node_modules
branches:
  only: master
  
before_install:  
 - export CHROME_BIN=/usr/bin/google-chrome 
 - sudo apt-get update 
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
 - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
 - sudo apt-get update
 - sudo apt-get install google-chrome-stable

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip
  - mkdir -o chromedriver
  - unzip -o chromedriver_linux64.zip -C chromedriver
  - export PATH=$PATH:$PWD/chromedriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm i -g npm@^3
  - sleep 3 
  
cache: pip
install:
  - pip install biopython
  - pip install mygene
  - pip install selenium
  
script:
  - python Starter.py Gene_acd_ensemble_ID.csv
