language: python
python:
  - "2.7"
  
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - google-chrome-stable

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.9/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
  
cache: pip
install:
  - pip install biopython
  - pip install mygene
  - pip install selenium
  
script:
  - python Starter.py Gene_acd_ensemble_ID.csv
