language: python
python:
  - "2.7"

dist: trusty
sudo: required
 
cache: pip
install:
 - pip install biopython
 - pip install mygene
 - pip install selenium
 
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 
before_install:  
 - export CHROME_BIN=/usr/bin/google-chrome 
 - sudo apt-get update 
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
 - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
 - sudo apt-get update
 - sudo apt-get install google-chrome-stable
 
env:
 global:
    - CHROME_REVISION=`curl -s http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/LAST_CHANGE`
    - CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
    - PATH=$PATH:$PWD/chrome-linux
 
script:
 - export CHROME_REVISION=`curl -s http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/LAST_CHANGE`
 - export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
 - curl -L -O "http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/${CHROME_REVISION}/chrome-linux.zip"
 - unzip chrome-linux.zip

 - curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
 - unzip -o chromedriver_linux64.zip

 - chmod +x chromedriver
 - mv chromedriver chrome-linux/chromedriver
 - export PATH=$PATH:$PWD/chrome-linux

 - export CHROME_BINARY=$PWD/chrome-linux/chrome
 - export CHROMEDRIVER=$PWD/chrome-linux/chromedriver
 - python Starter.py Gene_acd_ensemble_ID.csv
 - zip -r Output.zip $TRAVIS_BUILD_DIR/Output
  
deploy:
  provider: releases
  api_key:
    secure: 119aae08f206ee98a439eff21442483baed7c90e
  file:
   - Output.zip
  skip_cleanup: true
  on:
    tags: true
    
notifications:
 on success: never

